name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # - name: Run tests
      #   run: yarn test

      - name: Build Docker image
        run: docker build -t bookstack-ci-backend .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 905418341123.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push Docker image to ECR
        run: |
          docker build -t bookstack-ci-backend .
          docker tag bookstack-ci-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/bookstack-ci-backend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/bookstack-ci-backend:latest

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false \
          -var "mongo_uri=${{ secrets.MONGO_URI }}" \
          -var "jwt_secret=${{ secrets.JWT_SECRET }}" \
          -var "aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
          -var "environment=prod"

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -input=false -auto-approve \
          -var "mongo_uri=${{ secrets.MONGO_URI }}" \
          -var "jwt_secret=${{ secrets.JWT_SECRET }}" \
          -var "aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
          -var "environment=prod"
